name       : python-charset-normalizer
version    : 3.1.0
release    : 7
source     :
    - https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-3.1.0.tar.gz : 34e0a2f9c370eb95597aae63bf85eb5e96826d81e3dcf88b8886012906f509b5
homepage   : https://github.com/ousret/charset_normalizer
license    : MIT
component  : programming.python
summary    : Truly universal encoding detector in pure Python
description: |
    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
