name       : python-charset-normalizer
version    : 2.0.7
release    : 2
source     :
    - https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.0.7.tar.gz : e019de665e2bcf9c2b64e2e5aa025fa991da8720daa3c1138cadd2fd1856aed0
license    : MIT
component  : programming.python
summary    : The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
description: |
    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
