name       : python-charset-normalizer
version    : 2.0.12
release    : 4
source     :
    - https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.0.12.tar.gz : 2857e29ff0d34db842cd7ca3230549d1a697f96ee6d3fb071cfa6c7393832597
homepage   : https://github.com/ousret/charset_normalizer
license    : MIT
component  : programming.python
summary    : Truly universal encoding detector in pure Python
description: |
    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
