name       : python-charset-normalizer
version    : 2.1.0
release    : 5
source     :
    - https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.1.0.tar.gz : 575e708016ff3a5e3681541cb9d79312c416835686d054a23accb873b254f413
homepage   : https://github.com/ousret/charset_normalizer
license    : MIT
component  : programming.python
summary    : Truly universal encoding detector in pure Python
description: |
    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
