name       : python-charset-normalizer
version    : 2.1.1
release    : 6
source     :
    - https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.1.1.tar.gz : 5a3d016c7c547f69d6f81fb0db9449ce888b418b5b9952cc5e6e66843e9dd845
homepage   : https://github.com/ousret/charset_normalizer
license    : MIT
component  : programming.python
summary    : Truly universal encoding detector in pure Python
description: |
    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
