name       : python-charset-normalizer
version    : 2.0.4
release    : 1
source     :
    - https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.0.4.tar.gz : f23667ebe1084be45f6ae0538e4a5a865206544097e4e8bbcacf42cd02a348f3
license    : MIT
component  : programming.python
summary    : The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
description: |
    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
